#!/usr/bin/env escript
%% -*- erlang -*-
%%! -sasl errlog_type error -boot start_sasl -noshell -erl_libs /home/vasco/w/dia-test/erlang-rts-part-3/deps/protobuffs/ebin

main ([File]) ->
  protobuffs_compile:generate_source (File);
main (_) ->
  io:format ("usage: ~s <protofile>~n",
             [filename:basename (escript:script_name())]),
  halt (1).
